
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2025-02-05T18:24:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a16580d9d5ed57166e3b1eec3d4fccd3eeef1eb",
 "version": "2.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
